/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Berita = {
  _id: string;
  _type: "berita";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  judul?: string;
  slug?: Slug;
  publishedAt?: string;
  isi?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Kegiatan = {
  _id: string;
  _type: "kegiatan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  date?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type DataSekolah = {
  _id: string;
  _type: "dataSekolah";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  visi?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  misi?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tujuan?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  prestasi?: Array<{
    judul?: string;
    tahun?: number;
    namaSiswa?: string;
    _type: "prestasiItem";
    _key: string;
  }>;
  fasilitas?: Array<string>;
  akreditasi?: string;
  totalSiswa?: number;
  jumlahSiswa?: number;
  alamat?: string;
  telepon?: string;
  email?: string;
  sosmed?: {
    instagram?: string;
    youtube?: string;
    tiktok?: string;
  };
};

export type Artikel = {
  _id: string;
  _type: "artikel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  judul?: string;
  slug?: Slug;
  guru?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "guru";
  };
  gambar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  isi?: BlockContent;
};

export type Guru = {
  _id: string;
  _type: "guru";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nama?: string;
  slug?: Slug;
  jabatan?: string;
  foto?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Berita | BlockContent | Slug | Kegiatan | SanityImageCrop | SanityImageHotspot | DataSekolah | Artikel | Guru | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: ARTIKEL_LIST_QUERY
// Query: *[  _type == "artikel"  && defined(slug.current)]|order(publishedAt desc)[0...12]{  _id,  judul,  slug,  publishedAt,  "guruNama": guru->nama,  gambar{    ...,    alt  }}
export type ARTIKEL_LIST_QUERYResult = Array<{
  _id: string;
  judul: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  guruNama: string | null;
  gambar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
}>;
// Variable: ARTIKEL_DETAIL_QUERY
// Query: *[  _type == "artikel"  && slug.current == $slug][0]{  _id,  judul,  slug,  publishedAt,  "guruNama": guru->nama,  gambar{    ...,    alt  },  isi}
export type ARTIKEL_DETAIL_QUERYResult = {
  _id: string;
  judul: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  guruNama: string | null;
  gambar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  isi: BlockContent | null;
} | null;
// Variable: BERITA_LIST_QUERY
// Query: *[  _type == "berita"  && defined(slug.current)]|order(publishedAt desc)[0...12]{  _id,  judul,  slug,  publishedAt}
export type BERITA_LIST_QUERYResult = Array<{
  _id: string;
  judul: string | null;
  slug: Slug | null;
  publishedAt: string | null;
}>;
// Variable: BERITA_DETAIL_QUERY
// Query: *[  _type == "berita"  && slug.current == $slug][0]{  _id,  judul,  slug,  publishedAt,  isi}
export type BERITA_DETAIL_QUERYResult = {
  _id: string;
  judul: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  isi: BlockContent | null;
} | null;
// Variable: GURU_LIST_QUERY
// Query: *[  _type == "guru"  && defined(slug.current)]|order(nama asc){  _id,  nama,  slug,  jabatan,  foto,  bio}
export type GURU_LIST_QUERYResult = Array<{
  _id: string;
  nama: string | null;
  slug: Slug | null;
  jabatan: string | null;
  foto: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: string | null;
}>;
// Variable: GURU_DETAIL_QUERY
// Query: *[  _type == "guru"  && slug.current == $slug][0]{  _id,  nama,  slug,  jabatan,  foto,  bio}
export type GURU_DETAIL_QUERYResult = {
  _id: string;
  nama: string | null;
  slug: Slug | null;
  jabatan: string | null;
  foto: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: string | null;
} | null;
// Variable: KEGIATAN_LIST_QUERY
// Query: *[  _type == "kegiatan"]|order(date desc){  _id,  title,  date,  images[]{    ...,    alt  }}
export type KEGIATAN_LIST_QUERYResult = Array<{
  _id: string;
  title: string | null;
  date: string | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
    _key: string;
  }> | null;
}>;
// Variable: KEGIATAN_DETAIL_QUERY
// Query: *[  _type == "kegiatan"  && _id == $id][0]{  _id,  title,  date,  images[]{    ...,    alt  }}
export type KEGIATAN_DETAIL_QUERYResult = {
  _id: string;
  title: string | null;
  date: string | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: DATA_SEKOLAH_QUERY
// Query: *[  _type == "dataSekolah"][0]{  _id,  visi,  misi,  tujuan,  prestasi[]{    judul,    tahun,    namaSiswa  },  fasilitas,  akreditasi,  totalSiswa,  jumlahSiswa,  alamat,  telepon,  email,  sosmed{    instagram,    youtube,    tiktok  }}
export type DATA_SEKOLAH_QUERYResult = {
  _id: string;
  visi: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  misi: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  tujuan: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  prestasi: Array<{
    judul: string | null;
    tahun: number | null;
    namaSiswa: string | null;
  }> | null;
  fasilitas: Array<string> | null;
  akreditasi: string | null;
  totalSiswa: number | null;
  jumlahSiswa: number | null;
  alamat: string | null;
  telepon: string | null;
  email: string | null;
  sosmed: {
    instagram: string | null;
    youtube: string | null;
    tiktok: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"artikel\"\n  && defined(slug.current)\n]|order(publishedAt desc)[0...12]{\n  _id,\n  judul,\n  slug,\n  publishedAt,\n  \"guruNama\": guru->nama,\n  gambar{\n    ...,\n    alt\n  }\n}": ARTIKEL_LIST_QUERYResult;
    "*[\n  _type == \"artikel\"\n  && slug.current == $slug\n][0]{\n  _id,\n  judul,\n  slug,\n  publishedAt,\n  \"guruNama\": guru->nama,\n  gambar{\n    ...,\n    alt\n  },\n  isi\n}": ARTIKEL_DETAIL_QUERYResult;
    "*[\n  _type == \"berita\"\n  && defined(slug.current)\n]|order(publishedAt desc)[0...12]{\n  _id,\n  judul,\n  slug,\n  publishedAt\n}": BERITA_LIST_QUERYResult;
    "*[\n  _type == \"berita\"\n  && slug.current == $slug\n][0]{\n  _id,\n  judul,\n  slug,\n  publishedAt,\n  isi\n}": BERITA_DETAIL_QUERYResult;
    "*[\n  _type == \"guru\"\n  && defined(slug.current)\n]|order(nama asc){\n  _id,\n  nama,\n  slug,\n  jabatan,\n  foto,\n  bio\n}": GURU_LIST_QUERYResult;
    "*[\n  _type == \"guru\"\n  && slug.current == $slug\n][0]{\n  _id,\n  nama,\n  slug,\n  jabatan,\n  foto,\n  bio\n}": GURU_DETAIL_QUERYResult;
    "*[\n  _type == \"kegiatan\"\n]|order(date desc){\n  _id,\n  title,\n  date,\n  images[]{\n    ...,\n    alt\n  }\n}": KEGIATAN_LIST_QUERYResult;
    "*[\n  _type == \"kegiatan\"\n  && _id == $id\n][0]{\n  _id,\n  title,\n  date,\n  images[]{\n    ...,\n    alt\n  }\n}": KEGIATAN_DETAIL_QUERYResult;
    "*[\n  _type == \"dataSekolah\"\n][0]{\n  _id,\n  visi,\n  misi,\n  tujuan,\n  prestasi[]{\n    judul,\n    tahun,\n    namaSiswa\n  },\n  fasilitas,\n  akreditasi,\n  totalSiswa,\n  jumlahSiswa,\n  alamat,\n  telepon,\n  email,\n  sosmed{\n    instagram,\n    youtube,\n    tiktok\n  }\n}": DATA_SEKOLAH_QUERYResult;
  }
}
